import { getOctokit, isGitHubWriteEnabled } from "./client.js";
import type { FailureCluster, FixPlan } from "../../types.js";
import { logger } from "../../utils/logger.js";

export interface IssueDraft {
  mode: "dry_run" | "created";
  issue_title: string;
  issue_body_markdown: string;
  issue_url?: string;
  issue_number?: number;
}

export function renderIssueBody(
  cluster: FailureCluster,
  fixPlan: FixPlan | null,
): string {
  const fs = cluster.feature_summary as Record<string, unknown>;
  const lines: string[] = [];

  lines.push("## Summary");
  lines.push("");
  lines.push(
    `Failure cluster \`${cluster.cluster_id}\` with **${cluster.size}** traces.`,
  );
  lines.push(`Fingerprint: \`${cluster.fingerprint}\``);
  lines.push("");

  lines.push("## Impact");
  lines.push("");
  lines.push(`- **Cluster size**: ${cluster.size} traces`);
  lines.push(`- **Priority score**: ${cluster.priority_score.toFixed(2)}`);
  if (fs.trace_name) lines.push(`- **Trace name**: ${fs.trace_name}`);
  if (fs.route) lines.push(`- **Route**: ${fs.route}`);
  if (fs.prompt_version) lines.push(`- **Prompt version**: ${fs.prompt_version}`);
  lines.push("");

  lines.push("## Evidence");
  lines.push("");
  lines.push("### Symptoms");
  for (const s of cluster.symptoms) {
    lines.push(`- ${s}`);
  }
  lines.push("");

  if (cluster.root_cause_hypotheses.length > 0) {
    lines.push("### Suspected Root Causes");
    for (const h of cluster.root_cause_hypotheses) {
      lines.push(
        `- **${h.cause}** (confidence: ${(h.confidence * 100).toFixed(0)}%)`,
      );
      for (const e of h.evidence) {
        lines.push(`  - ${e}`);
      }
    }
    lines.push("");
  }

  lines.push("## Representative Traces");
  lines.push("");
  for (const tid of cluster.representative_trace_ids) {
    lines.push(`- \`${tid}\``);
  }
  lines.push("");

  if (fixPlan) {
    lines.push("## Recommended Actions");
    lines.push("");
    for (const a of fixPlan.actions) {
      lines.push(`${a.priority}. **[${a.owner}]** ${a.action}`);
      lines.push(`   - Expected impact: ${a.expected_impact}`);
    }
    lines.push("");

    if (fixPlan.experiment_plan.length > 0) {
      lines.push("## Evaluation Plan");
      lines.push("");
      for (const step of fixPlan.experiment_plan) {
        lines.push(`- [ ] ${step}`);
      }
      lines.push("");
    }
  }

  lines.push("## Done Criteria");
  lines.push("");
  lines.push("- [ ] correctness 평균 0.82 이상");
  lines.push("- [ ] faithfulness 0.85 이상");
  lines.push("- [ ] 동일 cluster 재발률 50% 이상 감소");
  lines.push("- [ ] p95 latency 15% 이상 악화 없음");
  lines.push("");
  lines.push("---");
  lines.push("*Generated by Trace-to-Fix MCP*");

  return lines.join("\n");
}

export async function createIssueDraft(opts: {
  repo: string;
  cluster: FailureCluster;
  fixPlan: FixPlan | null;
  titlePrefix?: string;
  labels?: string[];
  assignees?: string[];
  dryRun?: boolean;
}): Promise<IssueDraft> {
  const fs = opts.cluster.feature_summary as Record<string, unknown>;
  const title = [
    opts.titlePrefix ?? "[Trace-to-Fix]",
    fs.trace_name ?? "unknown",
    fs.route ?? "",
    opts.cluster.symptoms[0] ?? "failure",
    "cluster",
  ]
    .filter(Boolean)
    .join(" ");

  const body = renderIssueBody(opts.cluster, opts.fixPlan);

  if (opts.dryRun !== false) {
    return { mode: "dry_run", issue_title: title, issue_body_markdown: body };
  }

  if (!isGitHubWriteEnabled()) {
    throw new Error(
      "GitHub write is disabled. Set ENABLE_GITHUB_WRITE=true to create issues.",
    );
  }

  const [owner, repo] = opts.repo.split("/");
  if (!owner || !repo) {
    throw new Error(`Invalid repo format: ${opts.repo}. Expected owner/repo`);
  }

  const octokit = getOctokit();
  const res = await octokit.issues.create({
    owner,
    repo,
    title,
    body,
    labels: opts.labels,
    assignees: opts.assignees,
  });

  logger.info({ issue: res.data.number, url: res.data.html_url }, "Issue created");

  return {
    mode: "created",
    issue_title: title,
    issue_body_markdown: body,
    issue_url: res.data.html_url,
    issue_number: res.data.number,
  };
}
